### ISSUE TITLE
mongoDB User in database.config

### ISSUE THREAD

**Issue by robertangeles** [anlek/mongify#155]
Hi. What user does mongify use when it starts processing translation files? I've encountered a couple of issues related to permission similar  #129 when running mongoDB as a service and running mongify. But if I just call mongod in the shell and run mongify, no permission issues.

Thanks!

Rob

**Comment by anlek** [comment]
That's a great question Rob, and it's a bit outside of my full understanding (Unix related things). Best guess is it runs under the current user (aka run `whoami` in your terminal to see the user). I'd assume your system is starting up MongoDB and that might be running under root. However, I can't think of a reason it should prevent you from actually using Mongify with your database.

Issue #129 has a permission problem inside the database. The connection details (aka your `noSqlConnection` details) you've provided to connect to the DB don't allow modifications that Mongify is trying to do. The reason it works when you start it up MongoDB locally is probably due to it running a different database altogether. 

Hope that helps, good luck.

Andrew
