### ISSUE TITLE
Mongifying gets gradually slower until dies

### ISSUE THREAD

**Issue by r1pp3rj4ck** [anlek/mongify#49]
Because of the huge offsets, I couldn't mongify my table and it got gradually slower. Is it possible to change the query from
`SELECT * FROM foobar LIMIT 10000 OFFSET 1000000;`
to
`SELECT * FROM foobar WHERE id > 1000000 ORDER BY id ASC LIMIT 10000;`
where the id would be the latest imported id?

**Comment by marfis** [comment]
Hi there!

The execution time is raising exponentially when migrating a huge amount of unindex rows (LIMIT gets very expensive I think.)

We are migrating about 80 million rows (8000 runs, each run migrating 10000 rows).
The running time for each set of 10000 rows startet fast, but now the waiting time between each run is very high: the average migration of 10000 rows itself still takes 5 seconds, but there is a waiting time of 2.5 minutes between each run, raising.
We calculated a overall running time of 11.5 hours when the migration started, based on the time mongify used for each run in the beginning. The migration is running for about 4 days now (~6800 of 8000 runs done) and no end in sight...

MySQL and mongodb are running on the same host on which mongify is executed.

We think that this is a MySQL performance thingy based on missing indexes and not a mongify bug.
It would have been a good idea to partition the dataset on MySQL before executing the script, but with 80 million rows and a legacy/outdated scheme we had trouble operating MySQL in a performant way (partitioning and/or indexing would have taken weeks), which is why we decided to migrate... Ouroboros...

But may there is some advice you can give us on how to still accelerate the process.

Regards, marco:)

(It seems that the progress bar displayed for each run is just related to the mongodb write operations, not the mysql select - can your confirm this?)
