### ISSUE TITLE
Migration too slow

### ISSUE THREAD

**Issue by krsapkota** [anlek/mongify#52]
Is it normal for the migration to take 5-6 hrs to migrate 315MB of data? I feel like I am doing things wrong. Would appreciate any suggestions.

Thanks a lot!

**Comment by marfis** [comment]
Hi there!

The execution time is raising exponentially when migrating a huge amount of unindex rows (LIMIT gets very expensive I think.)

We are migrating about 80 million rows (8000 runs, each run migrating 10000 rows).
The running time for each set of 10000 rows startet fast, but now the waiting time between each run is very high: the average migration of 10000 rows itself still takes 5 seconds, but there is a waiting time of 2.5 minutes between each run, raising.
We calculated a overall running time of 11.5 hours when the migration started, based on the time mongify used for each run in the beginning. The migration is running for about 4 days now (~6800 of 8000 runs done) and no end in sight...

MySQL and mongodb are running on the same host on which mongify is executed.

We think that this is a MySQL performance thingy based on missing indexes and not a mongify bug.
It would have been a good idea to partition the dataset on MySQL before executing the script, but with 80 million rows and a legacy scheme we had trouble operating MySQL in a performant way (partitioning and/or indexing would have taken weeks), which is why we decided to migrate... Ouroboros...

But may there is some advice you can give us on how to still accelerate the process.

Regards, marco:)

(It seems that the progress bar displayed for each run is just related to the mongodb write operations, not the mysql select  - can your confirm this?)

**Comment by anlek** [comment]
it depends on your computer specs and how many references you have in your data.
I recently moved a 250mb database and it took a bit over an hour.
However I am running it on a computer that has 16 gigs of RAM and a 2.7 GHz Intel Core i7.
