### ISSUE TITLE
could not went into the database.config

### ISSUE THREAD

**Issue by davidwong750** [anlek/mongify#60]
hi everyone in mongify, whoever is viewing this, do help me.

i currently doing this project from SQL database to mongify which is what i doing now in this link. i have completed my "gem install mongify" but my next step going into database.config is fail. 

ubuntu version: 14.04
and as for ruby version: i not sure how to check...

**Comment by davidwong750** [comment]
hi. i just check my gem version is 2.4.6

**Comment by anlek** [comment]
Hey @davidwong750,
Try to run `ruby -v` to see the version of ruby.

Also, saying 'it fails' doesn't give enough information to give you hints on what's going on. Try to copy the error message or text after running the `gem install mongify` code. This will help me or others try to figure out what the issue is.

Take care,
Andrew
